# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: ":pkey"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.ssh/eliott_ed25519.pub"

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co/ip"

  - trigger: ":apt"
    replace: "apt-get update && apt-get dist-upgrade -y"

  - trigger: ":email"
    replace: "***REMOVED***"

  - trigger: ":tty"
    replace: ":set ttymouse="

  - trigger: ":shrug"
    replace: '¯\(ツ)/¯'

  - trigger: ":dex"
    replace: 'docker exec -it $|$ bash'

  - trigger: ":kex"
    replace: 'kubectl exec -it $|$ -- bash'

  - trigger: ":hacheck"
    replace: 'haproxy -c -V -f /etc/haproxy/haproxy.cfg'

  - trigger: ":md"
    replace: |-
      ```
      {{clipboard}}
      ```
    vars:
      - name: "clipboard"
        type: "clipboard"

