matches:
  - trigger: ":paste"
    form: "[[Content]]"
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  - regex: ":1024x(?P<num>.*);"
    replace: "{{result}}"
    vars:
      - name: result
        type: shell
        params:
          cmd: "res=$(($ESPANSO_NUM * 1024)); echo $res"

  - regex: ":mul\\((?P<num1>.*?),(?P<num2>.*?)\\)"
    replace: "{{result}}"
    vars:
      - name: result
        type: shell
        params:
          cmd: "res=$(($ESPANSO_NUM1 * $ESPANSO_NUM2)); echo $res"

  - trigger: ":pkey"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.ssh/id_ed25519.pub"

  - trigger: ":bwgen"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "bw generate"

  - trigger: ":pwgen"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "pwgen -n 30 -N 1"

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.me"

  - trigger: ":apt"
    replace: "apt update && apt dist-upgrade"

  - trigger: ":tty"
    replace: ":set ttymouse="

  - trigger: ":w!!"
    replace: ":w !sudo tee %"

  - trigger: ":shrug"
    replace: '¯\(ツ)/¯'
  - trigger: ":tableflip"
    replace: '(╯°□°）╯︵ ┻━┻'
  - trigger: ":tabledrop"
    replace: '┬─┬ノ( º _ ºノ)'

  - trigger: ":dex"
    replace: 'docker exec -it $|$ bash'

  - trigger: ":kex"
    replace: 'kubectl exec -it $|$ -- bash'

  - trigger: ":hacheck"
    replace: 'haproxy -c -V -f /etc/haproxy/haproxy.cfg'

  - trigger: ":md"
    replace: |-
      ```
      {{clipboard}}
      ```
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ":zellij"
    replace: "bash <(curl -L zellij.dev/launch)"

  - trigger: ":ntfy"
    replace: 'HOOK="https://ntfy.sh/ping_task_egoye" ; echo $HOOK; echo "$HOOK" | curl -F-=\<- qrenco.de; $|$ && MSG="Done" || MSG="Error" ; curl -d "$MSG" "$HOOK"'



