backend: Clipboard

matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: ":pkey"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat ~/.ssh/id_ed25519.pub"

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co/ip"

  - trigger: ":apt"
    replace: "apt-get update && apt-get dist-upgrade"

  - trigger: ":email"
    replace: "***REMOVED***"

  - trigger: ":tty"
    replace: ":set ttymouse="

  - trigger: ":w!!"
    replace: ":w !sudo tee %"

  - trigger: ":shrug"
    replace: '¯\(ツ)/¯'

  - trigger: ":dex"
    replace: 'docker exec -it $|$ bash'

  - trigger: ":kex"
    replace: 'kubectl exec -it $|$ -- bash'

  - trigger: ":hacheck"
    replace: 'haproxy -c -V -f /etc/haproxy/haproxy.cfg'

  - trigger: ":md"
    replace: |-
      ```
      {{clipboard}}
      ```
    vars:
      - name: "clipboard"
        type: "clipboard"

